version: '3'

services:
  sender:
    image: custom/multicast/message-sender
    volumes:
      - ./logs:/opt/udp/sender/logs
      - ./config:/opt/udp/sender/config
    networks:
      - netipvlan
  receiver:
    image: custom/multicast/message-receiver
    volumes:
      - ./logs:/opt/udp/receiver/logs
      - ./config:/opt/udp/receiver/config
    networks:
      - netipvlan

networks:
  netipvlan:
    external: true
